In [1]:
import numpy as np

In [7]:
#array 1d
d1 = np.array([1,2,3])

In [8]:
d1.shape

(3,)

In [9]:
d1.ndim

1

In [10]:
d1.dtype

dtype('int64')

In [12]:
a = np.array([[2,3,4,5], [6,7,8,9]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [13]:
#item especifico, ordem linha coluna
a[1,2]

8

In [14]:
#mostrar toda uma linha
a[0,:]

array([2, 3, 4, 5])

In [16]:
#mostrar todas as colunas
a[:,1]

array([3, 7])